version: '2'
services:
  api:
    image: mattjvincent/rqtlapi
    volumes:
     - ./data:/api/data
     - ./R:/api/R
    ports:
     - 8000

  lb:
    image: tutum/haproxy
    ports:
      - 18889:80
      - 11936:1936
    environment:
      - TIMEOUT=connect 5000, client 300000, server 300000
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
