version: '2'
services:
  webapi:
    image: mattjvincent/rqtlapi
    volumes:
     - ./data:/api/data
     - ./R:/api/R
    ports:
     - "8000"

  haproxy:
    image: dockercloud/haproxy:1.6.2
    ports:
      - "18889:80"
      - "11936:1936"
    environment:
      - TIMEOUT=connect 5000, client 300000, server 300000
    links:
      - webapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
